#include "controles.h"

char* DEBUG_CONTROLS[LA_CONTROL_LENGTH] = {
	"LA_PLAYPAUSE",
	"LA_UP",
	"LA_DOWN",
	"LA_LEFT",
	"LA_RIGHT",
	"LA_MENU",
	"LA_OK",
	"LA_STOP",
	"LA_EXIT",
	"LA_RADIO_INTER",
	"LA_RADIO_RENNES",
	"LA_RADIO_CANALB",
	"LA_PODCAST_DEGUSTER"
};
